import {
  Target,
  Sword,
  ArrowLeftRight,
  Rocket,
  Eye,
  Scan,
  Radio,
  ZoomIn,
  HelpCircle,
  Users,
  Globe,
  Database,
  Map,
  Package,
  Circle,
} from 'lucide-preact';

export const Icons = {
  Aimbot: Target,
  MeleeLock: Sword,
  AutoSwitch: ArrowLeftRight,
  SemiAuto: Rocket,
  XRay: Eye,
  LayerSpoof: Scan,
  ESP: Radio,
  InfiniteZoom: ZoomIn,
  Help: HelpCircle,
  Community: Users,
  Website: Globe,
  Credits: Database,
  Map: Map,
  AutoLoot: Package,
  MobileMovement: Circle,
};
