import {
  Target,
  Sword,
  ArrowLeftRight,
  Rocket,
  Eye,
  Scan,
  Radio,
  ZoomIn,
  HelpCircle,
  Users,
  Globe,
  Database,
  Map,
  Package,
  Circle,
} from 'lucide-preact';

export const Icons = {
  Aimbot_: Target,
  MeleeLock_: Sword,
  AutoSwitch_: ArrowLeftRight,
  SemiAuto_: Rocket,
  XRay_: Eye,
  LayerSpoof_: Scan,
  ESP_: Radio,
  InfiniteZoom_: ZoomIn,
  Help_: HelpCircle,
  Community_: Users,
  Website_: Globe,
  Credits_: Database,
  Map_: Map,
  AutoLoot_: Package,
  MobileMovement_: Circle,
};
