export const styles = {
  global: {
    fontFamily: "'GothamPro', sans-serif",
    boxSizing: 'border-box',
    margin: 0,
    padding: 0,
  },
  popup: {
    userSelect: 'none',
    position: 'relative',
    background: '#131313',
    borderRadius: '15px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
    width: '340px',
    overflow: 'hidden',
    border: '1px solid #333',
    transition: 'all 0.3s ease-out',
  },
  header: {
    background: '#181818',
    padding: '10px',
    borderBottom: '1px solid #313131',
    userSelect: 'none',
    transition: 'all 0.1s ease',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  headerAfter: {
    content: '',
    position: 'absolute',
    bottom: '-1px',
    left: 0,
    right: 0,
    height: '1px',
    background: 'linear-gradient(90deg, transparent, #5b5b5b 50%, transparent)',
  },
  menuIcon: {
    height: '20px',
    pointerEvents: 'none',
    position: 'absolute',
    left: '6px',
    top: '7px',
  },
  navbar: {
    background: '#161616',
    padding: '8px',
    borderBottom: '1px solid #333',
  },
  title: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#fff',
    textAlign: 'center',
    position: 'relative',
    zIndex: 1,
  },
  credit: {
    fontSize: '12px',
    fontStyle: 'italic',
    color: 'rgba(255, 255, 255, 0.45)',
    textAlign: 'center',
    display: 'block',
    position: 'relative',
    zIndex: 1,
  },
  navTabs: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s ease',
  },
  navTab: {
    padding: '6px 12px',
    background: '#202020',
    border: 'none',
    borderRadius: '4.5px',
    color: '#bababa',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'transform 0.1s ease',
  },
  navTabActive: {
    color: '#fff',
    border: '1px solid #6f6f6f',
    transform: 'translateY(-1px)',
  },
  closeBtn: {
    position: 'absolute',
    top: '1px',
    right: '8px',
    cursor: 'pointer',
    border: 'none',
    background: 'none',
    fontSize: '20px',
    color: '#666',
    transition: 'all 0.2s ease',
  },
  contentContainer: {
    paddingTop: '10px',
    paddingLeft: '16px',
    paddingRight: '16px',
    display: 'none',
  },
  contentContainerActive: {
    display: 'block',
  },
  section: {
    marginBottom: '20px',
  },
  sectionTitle: {
    color: '#fff',
    fontSize: '13px',
    fontWeight: 600,
    margin: '0 0 6px 0',
    letterSpacing: '0.5px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '6px',
  },
  sectionTitleContainer: {
    flexGrow: 1,
  },
  subsectionTitle: {
    color: '#bbb',
    fontSize: '12px',
    fontWeight: 600,
    margin: '14px 0 4px 15px',
    position: 'relative',
  },
  group: {
    display: 'flex',
    flexDirection: 'column',
    background: 'rgba(255, 255, 255, 0.02)',
    borderRadius: '8px',
    padding: '10px',
    marginBottom: '10px',
    gap: '6px',
    border: '1px solid rgba(255,255,255,0.1)',
    transition: 'all 0.1s ease, transform 0.1s ease',
  },
  subgroup: {
    marginLeft: '15px',
    borderLeft: '2px solid rgba(255, 255, 255, 0.1)',
    paddingLeft: '10px',
  },
  checkboxItem: {
    border: '1px solid #2c2c2c',
    display: 'inline-flex',
    alignItems: 'center',
    padding: '6px 8px 6px 8px',
    borderRadius: '6px',
    transition: 'background 0.2s ease',
    cursor: 'pointer',
    width: 'fit-content',
    backgroundColor: 'rgba(0, 0, 0, 0.04)',
  },
  checkboxItemLabel: {
    color: '#ddd',
    fontSize: '13px',
    marginLeft: '8px',
    cursor: 'pointer',
    pointerEvents: 'none',
  },
  checkbox: {
    appearance: 'none',
    width: '16px',
    height: '14px',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: '#888',
    borderRadius: '4px',
    background: '#222',
    position: 'relative',
    transition: 'all 0.1s cubic-bezier(0.68, -0.55, 0.27, 1.55)',
    cursor: 'pointer',
  },
  checkboxChecked: {
    background: '#66db6a',
    borderColor: '#66db6a',
    boxShadow: '0 0 10px rgba(102, 219, 106, 0.12)',
  },
  sliderContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  slider: {
    appearance: 'none',
    width: '90px',
    height: '5px',
    background: '#333',
    borderRadius: '5px',
    outline: 'none',
    cursor: 'pointer',
  },
  keybindSlot: {
    width: '28px',
    height: '12px',
    backgroundColor: '#2a2a2a',
    color: '#888',
    fontSize: '9px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '4px',
  },
  helpSection: {
    fontSize: '13px',
  },
  helpTitle: {
    color: 'white',
    fontSize: '15px',
    marginBottom: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontWeight: 600,
  },
  helpPanel: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '8px',
    padding: '10px',
    marginBottom: '12px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
  },
  keybindButton: {
    background: '#333',
    color: '#fff',
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 600,
  },
  keybindDescription: {
    marginLeft: '10px',
    color: '#fff',
    fontSize: '13px',
  },
  keybindHelpText: {
    color: '#bbb',
    fontSize: '12px',
    lineHeight: 1.4,
    margin: 0,
  },
  discordPanel: {
    background: 'rgba(88, 101, 242, 0.15)',
    borderRadius: '8px',
    padding: '10px',
    marginBottom: '12px',
    border: '1px solid rgba(88, 101, 242, 0.3)',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: '150px',
  },
  websitePanel: {
    background: 'rgba(105, 247, 76, 0.1)',
    borderRadius: '8px',
    padding: '10px',
    marginBottom: '12px',
    border: '1px solid rgba(105, 247, 76, 0.3)',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: '150px',
  },
  discordLink: {
    display: 'block',
    background: 'rgba(88, 101, 242, 0.3)',
    color: '#fff',
    textDecoration: 'none',
    padding: '8px',
    borderRadius: '6px',
    fontSize: '13px',
    textAlign: 'center',
    fontWeight: 600,
    border: '1px solid rgba(88, 101, 242, 0.5)',
    transition: 'all 0.3s ease-out',
    marginTop: 'auto',
  },
  websiteLink: {
    display: 'block',
    background: 'rgba(105, 247, 76, 0.15)',
    color: '#fff',
    textDecoration: 'none',
    padding: '8px',
    borderRadius: '6px',
    fontSize: '13px',
    textAlign: 'center',
    fontWeight: 600,
    border: '1px solid rgba(105, 247, 76, 0.3)',
    transition: 'all 0.3s ease-out',
    marginTop: 'auto',
  },
  creditsPanel: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '8px',
    padding: '10px',
    marginBottom: '12px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
  },
  creditsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '16px',
    color: '#ddd',
    fontSize: '13px',
  },
  creditItem: {
    flex: 1,
    minWidth: '120px',
  },
  creditName: {
    fontWeight: 600,
    marginBottom: '4px',
    color: '#fff',
  },
  sectionSubtitle: {
    color: '#fff',
    fontSize: '14px',
    marginBottom: '8px',
    fontWeight: 600,
  },
  featuresContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '8px',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    borderRadius: '6px',
  },
  featureName: {
    color: '#fff',
    fontSize: '13px',
    marginRight: '6px',
  },
  communityContainer: {
    display: 'flex',
    gap: '12px',
    marginBottom: '12px',
  },
};
